/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'
import { Route as ServicesWebsitesRouteImport } from './routes/services.websites'
import { Route as ServicesSupportRouteImport } from './routes/services.support'
import { Route as ServicesBotsRouteImport } from './routes/services.bots'
import { Route as MediaFileRouteImport } from './routes/media.$file'
import { Route as ApiMediaRouteImport } from './routes/api.media'
import { Route as ApiLeadRouteImport } from './routes/api.lead'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ServicesWebsitesIndexRouteImport } from './routes/services.websites.index'
import { Route as ServicesBotsIndexRouteImport } from './routes/services.bots.index'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as AdminCasesIndexRouteImport } from './routes/admin.cases.index'
import { Route as ServicesWebsitesLandingRouteImport } from './routes/services.websites.landing'
import { Route as ServicesWebsitesEcommerceRouteImport } from './routes/services.websites.ecommerce'
import { Route as ServicesWebsitesCorporateRouteImport } from './routes/services.websites.corporate'
import { Route as ServicesBotsTelegramRouteImport } from './routes/services.bots.telegram'
import { Route as ServicesBotsMiniappRouteImport } from './routes/services.bots.miniapp'
import { Route as ServicesBotsMaxRouteImport } from './routes/services.bots.max'
import { Route as AdminContentPackagesRouteImport } from './routes/admin.content.packages'
import { Route as AdminContentFaqRouteImport } from './routes/admin.content.faq'
import { Route as AdminContentContactsRouteImport } from './routes/admin.content.contacts'
import { Route as AdminCasesNewRouteImport } from './routes/admin.cases.new'
import { Route as AdminCasesSlugRouteImport } from './routes/admin.cases.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AdminContentServicesIndexRouteImport } from './routes/admin.content.services.index'
import { Route as AdminContentSeoIndexRouteImport } from './routes/admin.content.seo.index'
import { Route as AdminContentSectionsIndexRouteImport } from './routes/admin.content.sections.index'
import { Route as AdminContentServicesSlugRouteImport } from './routes/admin.content.services.$slug'
import { Route as AdminContentSeoSlugRouteImport } from './routes/admin.content.seo.$slug'
import { Route as AdminContentSectionsSlugRouteImport } from './routes/admin.content.sections.$slug'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorksRoute,
} as any)
const ServicesWebsitesRoute = ServicesWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSupportRoute = ServicesSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBotsRoute = ServicesBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => ServicesRoute,
} as any)
const MediaFileRoute = MediaFileRouteImport.update({
  id: '/media/$file',
  path: '/media/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWebsitesIndexRoute = ServicesWebsitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesWebsitesRoute,
} as any)
const ServicesBotsIndexRoute = ServicesBotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesBotsRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesIndexRoute = AdminCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesWebsitesLandingRoute = ServicesWebsitesLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => ServicesWebsitesRoute,
} as any)
const ServicesWebsitesEcommerceRoute =
  ServicesWebsitesEcommerceRouteImport.update({
    id: '/ecommerce',
    path: '/ecommerce',
    getParentRoute: () => ServicesWebsitesRoute,
  } as any)
const ServicesWebsitesCorporateRoute =
  ServicesWebsitesCorporateRouteImport.update({
    id: '/corporate',
    path: '/corporate',
    getParentRoute: () => ServicesWebsitesRoute,
  } as any)
const ServicesBotsTelegramRoute = ServicesBotsTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => ServicesBotsRoute,
} as any)
const ServicesBotsMiniappRoute = ServicesBotsMiniappRouteImport.update({
  id: '/miniapp',
  path: '/miniapp',
  getParentRoute: () => ServicesBotsRoute,
} as any)
const ServicesBotsMaxRoute = ServicesBotsMaxRouteImport.update({
  id: '/max',
  path: '/max',
  getParentRoute: () => ServicesBotsRoute,
} as any)
const AdminContentPackagesRoute = AdminContentPackagesRouteImport.update({
  id: '/content/packages',
  path: '/content/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentFaqRoute = AdminContentFaqRouteImport.update({
  id: '/content/faq',
  path: '/content/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentContactsRoute = AdminContentContactsRouteImport.update({
  id: '/content/contacts',
  path: '/content/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesNewRoute = AdminCasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesSlugRoute = AdminCasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentServicesIndexRoute =
  AdminContentServicesIndexRouteImport.update({
    id: '/content/services/',
    path: '/content/services/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentSeoIndexRoute = AdminContentSeoIndexRouteImport.update({
  id: '/content/seo/',
  path: '/content/seo/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentSectionsIndexRoute =
  AdminContentSectionsIndexRouteImport.update({
    id: '/content/sections/',
    path: '/content/sections/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentServicesSlugRoute =
  AdminContentServicesSlugRouteImport.update({
    id: '/content/services/$slug',
    path: '/content/services/$slug',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentSeoSlugRoute = AdminContentSeoSlugRouteImport.update({
  id: '/content/seo/$slug',
  path: '/content/seo/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentSectionsSlugRoute =
  AdminContentSectionsSlugRouteImport.update({
    id: '/content/sections/$slug',
    path: '/content/sections/$slug',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/works': typeof WorksRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/media': typeof ApiMediaRoute
  '/media/$file': typeof MediaFileRoute
  '/services/bots': typeof ServicesBotsRouteWithChildren
  '/services/support': typeof ServicesSupportRoute
  '/services/websites': typeof ServicesWebsitesRouteWithChildren
  '/works/$slug': typeof WorksSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/works/': typeof WorksIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/cases/$slug': typeof AdminCasesSlugRoute
  '/admin/cases/new': typeof AdminCasesNewRoute
  '/admin/content/contacts': typeof AdminContentContactsRoute
  '/admin/content/faq': typeof AdminContentFaqRoute
  '/admin/content/packages': typeof AdminContentPackagesRoute
  '/services/bots/max': typeof ServicesBotsMaxRoute
  '/services/bots/miniapp': typeof ServicesBotsMiniappRoute
  '/services/bots/telegram': typeof ServicesBotsTelegramRoute
  '/services/websites/corporate': typeof ServicesWebsitesCorporateRoute
  '/services/websites/ecommerce': typeof ServicesWebsitesEcommerceRoute
  '/services/websites/landing': typeof ServicesWebsitesLandingRoute
  '/admin/cases/': typeof AdminCasesIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/services/bots/': typeof ServicesBotsIndexRoute
  '/services/websites/': typeof ServicesWebsitesIndexRoute
  '/admin/content/sections/$slug': typeof AdminContentSectionsSlugRoute
  '/admin/content/seo/$slug': typeof AdminContentSeoSlugRoute
  '/admin/content/services/$slug': typeof AdminContentServicesSlugRoute
  '/admin/content/sections/': typeof AdminContentSectionsIndexRoute
  '/admin/content/seo/': typeof AdminContentSeoIndexRoute
  '/admin/content/services/': typeof AdminContentServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/media': typeof ApiMediaRoute
  '/media/$file': typeof MediaFileRoute
  '/services/support': typeof ServicesSupportRoute
  '/works/$slug': typeof WorksSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/works': typeof WorksIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/cases/$slug': typeof AdminCasesSlugRoute
  '/admin/cases/new': typeof AdminCasesNewRoute
  '/admin/content/contacts': typeof AdminContentContactsRoute
  '/admin/content/faq': typeof AdminContentFaqRoute
  '/admin/content/packages': typeof AdminContentPackagesRoute
  '/services/bots/max': typeof ServicesBotsMaxRoute
  '/services/bots/miniapp': typeof ServicesBotsMiniappRoute
  '/services/bots/telegram': typeof ServicesBotsTelegramRoute
  '/services/websites/corporate': typeof ServicesWebsitesCorporateRoute
  '/services/websites/ecommerce': typeof ServicesWebsitesEcommerceRoute
  '/services/websites/landing': typeof ServicesWebsitesLandingRoute
  '/admin/cases': typeof AdminCasesIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/services/bots': typeof ServicesBotsIndexRoute
  '/services/websites': typeof ServicesWebsitesIndexRoute
  '/admin/content/sections/$slug': typeof AdminContentSectionsSlugRoute
  '/admin/content/seo/$slug': typeof AdminContentSeoSlugRoute
  '/admin/content/services/$slug': typeof AdminContentServicesSlugRoute
  '/admin/content/sections': typeof AdminContentSectionsIndexRoute
  '/admin/content/seo': typeof AdminContentSeoIndexRoute
  '/admin/content/services': typeof AdminContentServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/works': typeof WorksRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/media': typeof ApiMediaRoute
  '/media/$file': typeof MediaFileRoute
  '/services/bots': typeof ServicesBotsRouteWithChildren
  '/services/support': typeof ServicesSupportRoute
  '/services/websites': typeof ServicesWebsitesRouteWithChildren
  '/works/$slug': typeof WorksSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/works/': typeof WorksIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/cases/$slug': typeof AdminCasesSlugRoute
  '/admin/cases/new': typeof AdminCasesNewRoute
  '/admin/content/contacts': typeof AdminContentContactsRoute
  '/admin/content/faq': typeof AdminContentFaqRoute
  '/admin/content/packages': typeof AdminContentPackagesRoute
  '/services/bots/max': typeof ServicesBotsMaxRoute
  '/services/bots/miniapp': typeof ServicesBotsMiniappRoute
  '/services/bots/telegram': typeof ServicesBotsTelegramRoute
  '/services/websites/corporate': typeof ServicesWebsitesCorporateRoute
  '/services/websites/ecommerce': typeof ServicesWebsitesEcommerceRoute
  '/services/websites/landing': typeof ServicesWebsitesLandingRoute
  '/admin/cases/': typeof AdminCasesIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/services/bots/': typeof ServicesBotsIndexRoute
  '/services/websites/': typeof ServicesWebsitesIndexRoute
  '/admin/content/sections/$slug': typeof AdminContentSectionsSlugRoute
  '/admin/content/seo/$slug': typeof AdminContentSeoSlugRoute
  '/admin/content/services/$slug': typeof AdminContentServicesSlugRoute
  '/admin/content/sections/': typeof AdminContentSectionsIndexRoute
  '/admin/content/seo/': typeof AdminContentSeoIndexRoute
  '/admin/content/services/': typeof AdminContentServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacts'
    | '/faq'
    | '/industries'
    | '/mcp'
    | '/packages'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/works'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/api/lead'
    | '/api/media'
    | '/media/$file'
    | '/services/bots'
    | '/services/support'
    | '/services/websites'
    | '/works/$slug'
    | '/admin/'
    | '/services/'
    | '/works/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/cases/$slug'
    | '/admin/cases/new'
    | '/admin/content/contacts'
    | '/admin/content/faq'
    | '/admin/content/packages'
    | '/services/bots/max'
    | '/services/bots/miniapp'
    | '/services/bots/telegram'
    | '/services/websites/corporate'
    | '/services/websites/ecommerce'
    | '/services/websites/landing'
    | '/admin/cases/'
    | '/admin/content/'
    | '/services/bots/'
    | '/services/websites/'
    | '/admin/content/sections/$slug'
    | '/admin/content/seo/$slug'
    | '/admin/content/services/$slug'
    | '/admin/content/sections/'
    | '/admin/content/seo/'
    | '/admin/content/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/faq'
    | '/industries'
    | '/mcp'
    | '/packages'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/api/lead'
    | '/api/media'
    | '/media/$file'
    | '/services/support'
    | '/works/$slug'
    | '/admin'
    | '/services'
    | '/works'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/cases/$slug'
    | '/admin/cases/new'
    | '/admin/content/contacts'
    | '/admin/content/faq'
    | '/admin/content/packages'
    | '/services/bots/max'
    | '/services/bots/miniapp'
    | '/services/bots/telegram'
    | '/services/websites/corporate'
    | '/services/websites/ecommerce'
    | '/services/websites/landing'
    | '/admin/cases'
    | '/admin/content'
    | '/services/bots'
    | '/services/websites'
    | '/admin/content/sections/$slug'
    | '/admin/content/seo/$slug'
    | '/admin/content/services/$slug'
    | '/admin/content/sections'
    | '/admin/content/seo'
    | '/admin/content/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacts'
    | '/faq'
    | '/industries'
    | '/mcp'
    | '/packages'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/works'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/api/lead'
    | '/api/media'
    | '/media/$file'
    | '/services/bots'
    | '/services/support'
    | '/services/websites'
    | '/works/$slug'
    | '/admin/'
    | '/services/'
    | '/works/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/cases/$slug'
    | '/admin/cases/new'
    | '/admin/content/contacts'
    | '/admin/content/faq'
    | '/admin/content/packages'
    | '/services/bots/max'
    | '/services/bots/miniapp'
    | '/services/bots/telegram'
    | '/services/websites/corporate'
    | '/services/websites/ecommerce'
    | '/services/websites/landing'
    | '/admin/cases/'
    | '/admin/content/'
    | '/services/bots/'
    | '/services/websites/'
    | '/admin/content/sections/$slug'
    | '/admin/content/seo/$slug'
    | '/admin/content/services/$slug'
    | '/admin/content/sections/'
    | '/admin/content/seo/'
    | '/admin/content/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  McpRoute: typeof McpRoute
  PackagesRoute: typeof PackagesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorksRoute: typeof WorksRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiMediaRoute: typeof ApiMediaRoute
  MediaFileRoute: typeof MediaFileRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof WorksRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof WorksRoute
    }
    '/services/websites': {
      id: '/services/websites'
      path: '/websites'
      fullPath: '/services/websites'
      preLoaderRoute: typeof ServicesWebsitesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/support': {
      id: '/services/support'
      path: '/support'
      fullPath: '/services/support'
      preLoaderRoute: typeof ServicesSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/bots': {
      id: '/services/bots'
      path: '/bots'
      fullPath: '/services/bots'
      preLoaderRoute: typeof ServicesBotsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/media/$file': {
      id: '/media/$file'
      path: '/media/$file'
      fullPath: '/media/$file'
      preLoaderRoute: typeof MediaFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/websites/': {
      id: '/services/websites/'
      path: '/'
      fullPath: '/services/websites/'
      preLoaderRoute: typeof ServicesWebsitesIndexRouteImport
      parentRoute: typeof ServicesWebsitesRoute
    }
    '/services/bots/': {
      id: '/services/bots/'
      path: '/'
      fullPath: '/services/bots/'
      preLoaderRoute: typeof ServicesBotsIndexRouteImport
      parentRoute: typeof ServicesBotsRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases/': {
      id: '/admin/cases/'
      path: '/cases'
      fullPath: '/admin/cases/'
      preLoaderRoute: typeof AdminCasesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/websites/landing': {
      id: '/services/websites/landing'
      path: '/landing'
      fullPath: '/services/websites/landing'
      preLoaderRoute: typeof ServicesWebsitesLandingRouteImport
      parentRoute: typeof ServicesWebsitesRoute
    }
    '/services/websites/ecommerce': {
      id: '/services/websites/ecommerce'
      path: '/ecommerce'
      fullPath: '/services/websites/ecommerce'
      preLoaderRoute: typeof ServicesWebsitesEcommerceRouteImport
      parentRoute: typeof ServicesWebsitesRoute
    }
    '/services/websites/corporate': {
      id: '/services/websites/corporate'
      path: '/corporate'
      fullPath: '/services/websites/corporate'
      preLoaderRoute: typeof ServicesWebsitesCorporateRouteImport
      parentRoute: typeof ServicesWebsitesRoute
    }
    '/services/bots/telegram': {
      id: '/services/bots/telegram'
      path: '/telegram'
      fullPath: '/services/bots/telegram'
      preLoaderRoute: typeof ServicesBotsTelegramRouteImport
      parentRoute: typeof ServicesBotsRoute
    }
    '/services/bots/miniapp': {
      id: '/services/bots/miniapp'
      path: '/miniapp'
      fullPath: '/services/bots/miniapp'
      preLoaderRoute: typeof ServicesBotsMiniappRouteImport
      parentRoute: typeof ServicesBotsRoute
    }
    '/services/bots/max': {
      id: '/services/bots/max'
      path: '/max'
      fullPath: '/services/bots/max'
      preLoaderRoute: typeof ServicesBotsMaxRouteImport
      parentRoute: typeof ServicesBotsRoute
    }
    '/admin/content/packages': {
      id: '/admin/content/packages'
      path: '/content/packages'
      fullPath: '/admin/content/packages'
      preLoaderRoute: typeof AdminContentPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/faq': {
      id: '/admin/content/faq'
      path: '/content/faq'
      fullPath: '/admin/content/faq'
      preLoaderRoute: typeof AdminContentFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/contacts': {
      id: '/admin/content/contacts'
      path: '/content/contacts'
      fullPath: '/admin/content/contacts'
      preLoaderRoute: typeof AdminContentContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases/new': {
      id: '/admin/cases/new'
      path: '/cases/new'
      fullPath: '/admin/cases/new'
      preLoaderRoute: typeof AdminCasesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases/$slug': {
      id: '/admin/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/admin/cases/$slug'
      preLoaderRoute: typeof AdminCasesSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/services/': {
      id: '/admin/content/services/'
      path: '/content/services'
      fullPath: '/admin/content/services/'
      preLoaderRoute: typeof AdminContentServicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/seo/': {
      id: '/admin/content/seo/'
      path: '/content/seo'
      fullPath: '/admin/content/seo/'
      preLoaderRoute: typeof AdminContentSeoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/sections/': {
      id: '/admin/content/sections/'
      path: '/content/sections'
      fullPath: '/admin/content/sections/'
      preLoaderRoute: typeof AdminContentSectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/services/$slug': {
      id: '/admin/content/services/$slug'
      path: '/content/services/$slug'
      fullPath: '/admin/content/services/$slug'
      preLoaderRoute: typeof AdminContentServicesSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/seo/$slug': {
      id: '/admin/content/seo/$slug'
      path: '/content/seo/$slug'
      fullPath: '/admin/content/seo/$slug'
      preLoaderRoute: typeof AdminContentSeoSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/sections/$slug': {
      id: '/admin/content/sections/$slug'
      path: '/content/sections/$slug'
      fullPath: '/admin/content/sections/$slug'
      preLoaderRoute: typeof AdminContentSectionsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCasesSlugRoute: typeof AdminCasesSlugRoute
  AdminCasesNewRoute: typeof AdminCasesNewRoute
  AdminContentContactsRoute: typeof AdminContentContactsRoute
  AdminContentFaqRoute: typeof AdminContentFaqRoute
  AdminContentPackagesRoute: typeof AdminContentPackagesRoute
  AdminCasesIndexRoute: typeof AdminCasesIndexRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminContentSectionsSlugRoute: typeof AdminContentSectionsSlugRoute
  AdminContentSeoSlugRoute: typeof AdminContentSeoSlugRoute
  AdminContentServicesSlugRoute: typeof AdminContentServicesSlugRoute
  AdminContentSectionsIndexRoute: typeof AdminContentSectionsIndexRoute
  AdminContentSeoIndexRoute: typeof AdminContentSeoIndexRoute
  AdminContentServicesIndexRoute: typeof AdminContentServicesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCasesSlugRoute: AdminCasesSlugRoute,
  AdminCasesNewRoute: AdminCasesNewRoute,
  AdminContentContactsRoute: AdminContentContactsRoute,
  AdminContentFaqRoute: AdminContentFaqRoute,
  AdminContentPackagesRoute: AdminContentPackagesRoute,
  AdminCasesIndexRoute: AdminCasesIndexRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminContentSectionsSlugRoute: AdminContentSectionsSlugRoute,
  AdminContentSeoSlugRoute: AdminContentSeoSlugRoute,
  AdminContentServicesSlugRoute: AdminContentServicesSlugRoute,
  AdminContentSectionsIndexRoute: AdminContentSectionsIndexRoute,
  AdminContentSeoIndexRoute: AdminContentSeoIndexRoute,
  AdminContentServicesIndexRoute: AdminContentServicesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesBotsRouteChildren {
  ServicesBotsMaxRoute: typeof ServicesBotsMaxRoute
  ServicesBotsMiniappRoute: typeof ServicesBotsMiniappRoute
  ServicesBotsTelegramRoute: typeof ServicesBotsTelegramRoute
  ServicesBotsIndexRoute: typeof ServicesBotsIndexRoute
}

const ServicesBotsRouteChildren: ServicesBotsRouteChildren = {
  ServicesBotsMaxRoute: ServicesBotsMaxRoute,
  ServicesBotsMiniappRoute: ServicesBotsMiniappRoute,
  ServicesBotsTelegramRoute: ServicesBotsTelegramRoute,
  ServicesBotsIndexRoute: ServicesBotsIndexRoute,
}

const ServicesBotsRouteWithChildren = ServicesBotsRoute._addFileChildren(
  ServicesBotsRouteChildren,
)

interface ServicesWebsitesRouteChildren {
  ServicesWebsitesCorporateRoute: typeof ServicesWebsitesCorporateRoute
  ServicesWebsitesEcommerceRoute: typeof ServicesWebsitesEcommerceRoute
  ServicesWebsitesLandingRoute: typeof ServicesWebsitesLandingRoute
  ServicesWebsitesIndexRoute: typeof ServicesWebsitesIndexRoute
}

const ServicesWebsitesRouteChildren: ServicesWebsitesRouteChildren = {
  ServicesWebsitesCorporateRoute: ServicesWebsitesCorporateRoute,
  ServicesWebsitesEcommerceRoute: ServicesWebsitesEcommerceRoute,
  ServicesWebsitesLandingRoute: ServicesWebsitesLandingRoute,
  ServicesWebsitesIndexRoute: ServicesWebsitesIndexRoute,
}

const ServicesWebsitesRouteWithChildren =
  ServicesWebsitesRoute._addFileChildren(ServicesWebsitesRouteChildren)

interface ServicesRouteChildren {
  ServicesBotsRoute: typeof ServicesBotsRouteWithChildren
  ServicesSupportRoute: typeof ServicesSupportRoute
  ServicesWebsitesRoute: typeof ServicesWebsitesRouteWithChildren
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBotsRoute: ServicesBotsRouteWithChildren,
  ServicesSupportRoute: ServicesSupportRoute,
  ServicesWebsitesRoute: ServicesWebsitesRouteWithChildren,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WorksRouteChildren {
  WorksSlugRoute: typeof WorksSlugRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

const WorksRouteChildren: WorksRouteChildren = {
  WorksSlugRoute: WorksSlugRoute,
  WorksIndexRoute: WorksIndexRoute,
}

const WorksRouteWithChildren = WorksRoute._addFileChildren(WorksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactsRoute: ContactsRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  McpRoute: McpRoute,
  PackagesRoute: PackagesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorksRoute: WorksRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiMediaRoute: ApiMediaRoute,
  MediaFileRoute: MediaFileRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
